config/routes.rb
Rails.application.routes.draw do
  mount Mercury::Engine => '/'

  root 'editable_pages#index'

  resources :editable_pages, :path => 'content', :except => [:show, :new] do
      collection do
          put 'mercury_update_index'
          put 'mercury_update_courses'
          get 'courses'
      end
  end

  devise_for :users

  resources :plays, :except => [:index] do
      collection do
          get 'upcoming'
          get 'archived'
      end
      member do
        get :download_all_pics
      end
  end

end

app/models/play.rb
class Play < ActiveRecord::Base
    mount_uploaders :pictures, ImageUploader
    mount_uploader :profile_image, ImageUploader

    serialize :pictures

    has_many :works_on
    has_many :users, :through => :works_on


    validates :title, presence: true
    validates :description, presence: true
    validates :date_of_play, presence: true
    validates :profile_image, presence: true

    before_save :format_data

    def format_data

      #convert user-supplied youtube video url to embedded url
      if link_to_video.present? and link_to_video.include?("youtube.com")

        #check if the url is already the correct embedded URL
        if link_to_video.include?("youtube.com/embed/")
          self.link_to_video = link_to_video
        else
          #find youtube video ID by parsing "https://www.youtube.com/watch?v=ID_VALUE" string
          video_id = link_to_video.split('v=')[1]
          ampersandPosition = video_id.index('&')
          if ampersandPosition != nil
            video_id = video_id.substring(0..ampersandPosition)
          end

          self.link_to_video = "https://www.youtube.com/embed/#{video_id}"
        end
      end

    end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
    before_action :set_play, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource
    skip_authorize_resource only: [:upcoming,:archived]
    #before_action :authenticate_user!, only: [:edit, :update, :destroy, :create] #only allow users to edit the DB, anyone can read. Note these routes are only called when someone clicks 'create' (or edit or delete), this doesn't stop the forms from being served

  ##############CUSTOM routes##############
  def upcoming
      @plays = Play.where("date_of_play >= ?",Time.now ).order(date_of_play: :desc )
  end

  def archived
      @plays = Play.where("date_of_play < ?",Time.now ).order(date_of_play: :desc )
  end

  def download_all_pics

  end

  ##############DEFAULT routes##############

  # GET /plays/1
  # GET /plays/1.json
  def show
  end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new(play_params)

    respond_to do |format|
      if @play.save
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render :show, status: :created, location: @play }
      else
        format.html { render :new }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { render :show, status: :ok, location: @play }
      else
        format.html { render :edit }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @play.destroy
    respond_to do |format|
      format.html { redirect_to plays_url, notice: 'Play was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
        params.require(:play).permit(:title, :description, :date_of_play,:profile_image,{:pictures=>[]},:link_to_video ) #weird notation around :pictures needed to permitted nested (array) attributes in this column field. Otherwise will be blocked by the strong_parameters gem
    end

end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/plays/_form.html.erb
<%= form_for(@play) do |f| %>
      <% if @play.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@play.errors.count, "error") %> prohibited this play from being saved:</h2>

          <ul>
          <% @play.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
          <%= f.text_area :description, class:"description" %>
      </div>
      <div class="field">
        <%= f.label :date_of_play %><br>
        <%= f.datetime_select :date_of_play %>
      </div>

      <div class="field">
        <%= f.label :profile_image %><br>
          <%= f.file_field :profile_image %>
          <!--
            <%= image_tag @play.profile_image.url(:thumb) if @play.profile_image.present? %>
            -->
      </div>

      <div class="field">
        <%= f.label :pictures %>
        <a class="editing-instructions" title="To upload multiple pictures, hold Shift and use arrowkeys. Or hold Ctrl and click each picture you want. Then submit by clicking 'Open' or hitting the 'Enter' key.">Hover here to learn how</a>
        <br>
        <%= f.file_field :pictures, multiple: true %>
      </div>

      <div class="field">
        <%= f.label :link_to_video %>
        <a class="editing-instructions" title="Copy and paste your 'https://www.youtube.com/' video's URL here">Hover here to learn how</a>
        <br>
        <%= f.text_field :link_to_video %>
      </div>


<!--
    <% @play.pictures.each{ |pic| %>
        <%= image_tag pic.url(:thumb)  %>
    <% } %>
-->

      <div class="actions">
        <%= f.submit %>
      </div>

    <% end %>

app/views/plays/archived.html.erb
<div id="show-all-plays">

    <% if @plays.count == 0 %>
      <p>There doesn't seem to be anything here</p>
    <% else
      curr_yr = @plays[0].date_of_play.year
      end %>

    <div id="<%= curr_yr %>"><!-- This div is required to initiate the first play grouping -->
    <%  @plays.each do |current_play| %>
        <% if(curr_yr != current_play.date_of_play.year)
              curr_yr = current_play.date_of_play.year%>
              <% puts "asdasd" %>
              </div>
              <div id="<%= curr_yr %>">
        <% end %>

        <%= render partial: "layouts/play_link" ,
            locals: {play: current_play} %>
    <% end %>
  </div> <!-- This div is required to end the final year grouping of the plays -->


</div>

app/views/plays/archived_plays.html.erb
<div id="show-all-plays">
    <% @plays.each do |current_play| %>
        <%= render partial: "layouts/play_link" , 
            locals: {play: current_play} %>
    <% end %>
</div>

app/views/plays/edit.html.erb
<h1>Editing Play</h1>

<%= render 'form' %>

<%= link_to 'Show', @play, class: 'btn btn-default' %> 
<%= link_to 'Back', plays_path, class: 'btn btn-default' %>

app/views/plays/new.html.erb
<h1>New Play</h1>

<%= render 'form' %>

app/views/plays/show.html.erb
<div id="show-one-play">
    <% if can? :update, @plays %>
        <%= link_to 'Edit', edit_play_path(@play), class: 'btn btn-primary' %>
    <% end %>

    <div class="row play-display">

        <div class="col-md-5" >
            <%= link_to( image_tag(@play.profile_image.url(:large_thumb)) , @play.profile_image.url)  %>
        </div>

        <div class="col-md-5 play-information">
            <h2><%= @play.title %> <small><%= @play.date_of_play.strftime("%B %d, %Y") %></small></h2>
            <p><%= @play.description %></p>
        </div>

    </div>

    <div class="play-video">
        <!-- display all pics from the play if they're present-->
        <% if @play.link_to_video.present? %>
        <iframe width="420" height="315"
        src="<%= @play.link_to_video %>">
        </iframe>
        <% end %>
    </div>

    <div class="play-pictures-list">
        <!-- display all pics from the play if they're present-->
        <% if @play.pictures.present? %>

            <%= link_to "Download all","#", class:"btn btn-default"%>

            <div class='play-pics-list'>
                <% @play.pictures.each{ |pic| %>
                    <%= link_to(image_tag(pic.url(:large_thumb)), pic.url)  %>
                <% } %>
            </div>
        <% end %>
    </div>
</div>

app/views/plays/upcoming.html.erb
<div id="show-all-plays">

    <% @plays.each do |current_play| %>
        <%= render partial: "layouts/play_link" ,
            locals: {play: current_play} %>
    <% end %>

    <% if @plays.count == 0 %>
      <p>There doesn't seem to be anything here</p>
    <% end %>


</div>

app/views/plays/upcoming_plays.html.erb
<div id="show-all-plays">
    <% @plays.each do |current_play| %>
        <%= render partial: "layouts/play_link" , 
            locals: {play: current_play} %>
    <% end %>
</div>