config/routes.rb
Rails.application.routes.draw do
  mount Mercury::Engine => '/'

  root 'editable_pages#index'

  resources :editable_pages, :path => 'content', :except => [:show, :new] do
      collection do
          put 'mercury_update_index'
          put 'mercury_update_courses'
          get 'courses'
      end
  end

  devise_for :users

  resources :plays, :except => [:index] do
      collection do
          get 'upcoming'
          get 'archived'
      end
      member do
        get :download_all_pics
      end
  end

end

app/models/editable_page.rb
class EditablePage < ActiveRecord::Base
end

app/controllers/editable_pages_controller.rb
class EditablePagesController < ApplicationController
  before_action :set_editable_page, only: [:show, :edit, :update, :destroy]

    def mercury_update_courses
        params[:content].each{|editable_field|
            css_id_label = editable_field[0]
            new_val = editable_field[1][:value]

            id = css_id_label.delete("^0-9")
            course = EditablePage.where("id = ?",id).last

            if css_id_label.index("title") != nil
                course.title = new_val
            elsif css_id_label.index("body") != nil
                course.body = new_val
            end

            course.save!
        }
        render text: ""
    end

    def mercury_update_index
        params[:content].each{|editable_field|
            css_id_label = editable_field[0]
            new_val = editable_field[1][:value]

            entity = EditablePage.where("classification = ?",css_id_label).last
            entity.body = new_val
            entity.save!
        }
        render text: ""
    end

    # GET /editable_pages/courses
    def courses
      @courses = EditablePage.where("classification = ?","courses")
    end

  # GET /editable_pages
  # GET /editable_pages.json
  def index
      @homepage_content_left = EditablePage.where("classification = ?","homepage_left").last
      @homepage_content_mid = EditablePage.where("classification = ?","homepage_mid").last
      @homepage_content_right = EditablePage.where("classification = ?","homepage_right").last
  end

  # GET /editable_pages/1/edit
  def edit
  end

  # POST /editable_pages
  # POST /editable_pages.json
  def create
    @editable_page = EditablePage.new(editable_page_params)

    respond_to do |format|
      if @editable_page.save
        format.html { redirect_to :back, notice: 'Successfully created.' }
        format.json { render :show, status: :created, location: @editable_page }
      else
        format.html { render :new }
        format.json { render json: @editable_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editable_pages/1
  # PATCH/PUT /editable_pages/1.json
  def update
    respond_to do |format|
      if @editable_page.update(editable_page_params)
        format.html { redirect_to :back, notice: 'Successfully updated.' }
        format.json { render :show, status: :ok, location: @editable_page }
      else
        format.html { render :edit }
        format.json { render json: @editable_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editable_pages/1
  # DELETE /editable_pages/1.json
  def destroy
    @editable_page.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_editable_page
      @editable_page = EditablePage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def editable_page_params
        params.require(:editable_page).permit(:classification,:title,:body)
    end
end

app/helpers/editable_pages_helper.rb
module EditablePagesHelper
end

app/views/editable_pages/_form.html.erb
<%= form_for(@editable_page) do |f| %>
  <% if @editable_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@editable_page.errors.count, "error") %> prohibited this editable_page from being saved:</h2>

      <ul>
      <% @editable_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editable_pages/courses.html.erb
<%
#functions for making the first element the active class
def add_active_class(index)
    if index==0
        return " active "
    end
end
def add_active_class_with_fadein(index)
    if index==0
        return " active in "#the 'in' class makes the tab content visible when page is first loaded
    end
end
%>


<% if can? :manage, @courses %>

    <!-- To get the Mercury editor interface on this page, navigate to ROOT/editor/courses -->
    <%= link_to "Edit Courses",
        "/editor"+courses_editable_pages_path,
        class:"btn btn-default",
        id:"edit_link", #Used in mercury.js to find this tag
data:{ save_url: mercury_update_courses_editable_pages_url } %>

    <%= link_to "Add Course",
        editable_pages_path(
            editable_page:{
                classification: 'courses',
                body:'Edit me!',
                title:"New Class"
                }
            ),
        :method=>:post,
        class:"btn btn-default" %>
<br/>
    <% if @courses != nil %>
      <% @courses.each do |course|%>
        <%= link_to "Delete #{ActionView::Base.full_sanitizer.sanitize(course.title)}", course, method: :delete, data: { confirm: 'Are you sure? This cannot be undone (but you can create new courses)!' },class:"btn btn-danger" %>
      <% end %>
    <% end %>

<% end %>

<% if @courses != nil and @courses.count > 0 %>
    <section id="class-tabs">
      <ul class="nav nav-tabs nav-justified" role="tablist">
          <% @courses.each_with_index do |course,index|%>
            <li class="<%=add_active_class(index)%> course-title" role="presentation">
                <a data-mercury="full" data-toggle="tab" id="<%= "course_title_id_is_#{course.id}" %>" href="#<%= "course_body_id_is_#{course.id}" %>" >
                  <%= raw course.title %>
              </a>
            </li>
          <% end %>
      </ul>

      <div class="tab-content">
          <% @courses.each_with_index do |course,index|%>
          <div id="<%= "course_body_id_is_#{course.id}" %>" data-mercury="full" class="tab-pane fade <%=add_active_class_with_fadein(index) %>">
                  <%= raw course.body %>
              </div>
          <% end %>

      </div>
    </section>
<% else %>
  <p>There doesn't seem to be anything here</p>
<% end %>

app/views/editable_pages/edit.html.erb
<h1>Editing Editable Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @editable_page %> |
<%= link_to 'Back', editable_pages_path %>

app/views/editable_pages/index.html.erb
<% if can? :manage, @homepage %>
    <%= link_to "Edit Page",
        "/editor",
        class:"btn btn-default",
        id:"edit_link", #Used in mercury.js to find this tag
data:{ save_url: mercury_update_index_editable_pages_url([@homepage_content_left,@homepage_content_mid,@homepage_content_right]) }
    %>
<% end %>


<div id="homepage">

    <% if @homepage_content_mid != nil and @homepage_content_left != nil and @homepage_content_right != nil %>
      <!-- This push, pull, and ordering of the left/mid is confusing, but it is here so that the left content is left on big screens, and underneath the mid content on small screens-->
      <div id="<%= @homepage_content_mid.classification %>" data-mercury="full" class="col-lg-6 col-lg-push-3">
          <%= raw @homepage_content_mid.body %>
      </div>

      <div id="<%= @homepage_content_left.classification %>" data-mercury="full" class="col-lg-3 col-lg-pull-6">
          <%= raw @homepage_content_left.body %>
      </div>

      <div id="<%= @homepage_content_right.classification %>" data-mercury="full" class="col-lg-3">
          <%= raw @homepage_content_right.body %>
      </div>
    <% else %>
      <p>There doesn't seem to be anything here</p>
    <% end %>
</div>

app/views/editable_pages/show.html.erb
<%= link_to 'Edit', edit_editable_page_path(@editable_page) %> |
<%= link_to 'Back', editable_pages_path %>