config/routes.rb
Rails.application.routes.draw do
  mount Mercury::Engine => '/'

  root 'editable_pages#index'

  resources :editable_pages, :path => 'content', :except => [:show, :new] do
      collection do
          put 'mercury_update_index'
          put 'mercury_update_courses'
          get 'courses'
      end
  end

  devise_for :users

  resources :plays, :except => [:index] do
      collection do
          get 'upcoming'
          get 'archived'
      end
      member do
        get :download_all_pics
      end
  end

end

app/views/layouts/_footer.html.erb
<footer>
    <div class="footer_left">
        <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, :method=>:delete,class:"btn btn-default"  %>
        <%else%>
            <%= link_to 'Login', new_user_session_path,class:"btn btn-default" %>
        <% end %>
    </div>
    
    <div class="footer_right">
        <p>gvarner@uaschools.org</p>
        <%= link_to 'UA Schools', "http://www.uaschools.org/"%>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <%= link_to root_path do %>
        <%= image_tag("uact.png") %>
        <span>Upper Arlington Community of Theatre</span>
    <% end %>
</header>

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <!--<%= link_to "UACT", root_path, class:"navbar-brand" %>-->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

          <li><%= nav_link 'Current Season', upcoming_plays_url %> </li>
          <li><%= nav_link 'Archives', archived_plays_url %> </li>
          <li><%= nav_link 'Courses', courses_editable_pages_url %> </li>
          <% if user_signed_in? %>
              <% if can? :manage, Play %>
                <li><%= nav_link "New Play", new_play_path %></li>
              <% end %>
              <li><%= link_to "Edit Profile", edit_user_registration_path(current_user.id) %></li>
          <% end %>

          <!--<li><%= nav_link 'Resources', "" %> </li>-->
          <!--<li><%= nav_link 'Plays', plays_path %>  </li>-->

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
            <% if user_signed_in? %>
                <p href="#" class="navbar-text">
                    Logged in as <strong><%= current_user.email %></strong>
                </p>
            <% end %>
        </li>
          <li>
              <%= link_to image_tag("twitter-icon.png", class:"navbar-icon"),'https://twitter.com/theatreua' %>
          </li>
          <li>
              <%= link_to image_tag("facebook-icon.png", class:"navbar-icon"),'https://www.facebook.com/pages/UACT-Upper-Arlington-Community-of-Theatre/128501485681?fref=ts' %>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_play_link.html.erb
<%= link_to "#{plays_path}/#{play.id}", class:'card' do %>
  <div class="card-img-wrap">
    <%= image_tag play.profile_image.url(:thumb) if play.profile_image.present? %>
  </div>
  <div class="card-content">
      <h4><%= play.title %></h4>
      <time><%= play.date_of_play.strftime("%B %d, %Y") %></time>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- make it possible to include custom CSS+javascript+whatever in individual html files -->
    <%= yield(:header) if @content_for_head %>

    <%= csrf_meta_tags %>
    <title>UACT : Upper Arlington Community of Theatre</title>
    <%= favicon_link_tag %>
</head>


<body>

        <!--
    <div>
        <% flash.each do |name,msg| %>
            <%= content_tag :div, msg, class:"flash #{name} alert alert-info" %>
        <% end %>
    </div>
        -->

    <div id="common-background-wrap">
        <div class="container-fluid" >
        <%= render :partial =>'layouts/header' %>
        <%= render :partial =>'layouts/navigation_bar' %>
            <!-- Devise check authentication -->
            <div>
                <% if notice %>
                  <p class="alert alert-success"><%= notice %></p>
                <% end %>
                <% if alert %>
                  <p class="alert alert-danger"><%= alert %></p>
                <% end %>
            </div>

            <section id="page-content">
              <%= yield %>
            </section>
        </div>
        <%= render :partial =>'layouts/footer' %>
    </div>

</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>